name: TEST OSS

on:
  workflow_dispatch:

jobs:
  yosys-vcxsrc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mmicko/setup-oss-cad-suite@v1
      - run: yosys --version
