name: Yosys Visual Studio

on:
  workflow_dispatch:

jobs:
  yosys-vcxsrc:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get yesterdays date
        id: yesterday
        run: echo "::set-output name=date::$(date --date="yesterday" +'%Y-%m-%d')"
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/yosys'
          ref: 'master'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: .
          key: cache-yosys
      - name: Build
        run: make vcxsrc YOSYS_VER=latest
