name: Yosys Visual Studio

on:
  workflow_dispatch:

jobs:
  yosys-vcxsrc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/yosys'
          ref: 'master'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: .
          key: cache-yosys
      - name: Build
        run: make vcxsrc YOSYS_VER=latest
      - uses: actions/upload-artifact@v2
        with:
          name: vcxsrc
          path: yosys-win32-vcxsrc-latest.zip
  
  build:
    runs-on: ubuntu-latest
    needs: yosys-vcxsrc
    steps:  
      - uses: actions/download-artifact@v2
        with:
          name: vcxsrc
          path: .
      - name: Build
        run: unzip yosys-win32-vcxsrc-latest.zip
