name: CI

on:
  workflow_dispatch:

jobs:
  linux-x64-sby:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get yesterdays date
        id: yesterday
        run: echo "::set-output name=date::$(date --date="yesterday" +'%Y-%m-%d')"
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
          ref: 'packages'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-sby-${{ steps.date.outputs.date }}
      - name: Cache output hash
        id: cache-hash
        uses: actions/cache@v2
        with:
          path: _hashes
          key: cache-hash-linux-x64-sby-${{ steps.date.outputs.date }}
          restore-keys: |
            cache-hash-linux-x64-sby-${{ steps.yesterday.outputs.date }}
            cache-hash-linux-x64-sby-
      - name: Build
        run: ./nightly.py build --no-update --arch=linux-x64 --target=sby
      - uses: ncipollo/release-action@v1
        if: hashFiles('_outputs/linux-x64/sby/*') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: fpga-nightly-${{ steps.date.outputs.date }}
          artifacts: "_outputs/linux-x64/sby/*.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}

