name: TEST OSS

on:
  workflow_dispatch:

jobs:
  test_oss_cad_suite:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mmicko/setup-oss-cad-suite@v1
      - run: yosys --version
