name: darwin-x64

on:
  workflow_dispatch:

jobs:
  darwin-x64-dfu-util:
    runs-on: macos-10.14
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-dfu-util
      - name: Download previous build
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/darwin-x64-dfu-util.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Install dependencies
        run: brew bundle
      - name: Build
        run: ./nightly.py build --arch=darwin-x64 --target=dfu-util --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('darwin-x64-dfu-util.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket
          artifacts: "darwin-x64-dfu-util.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
