name: test-build

on:
  workflow_dispatch:

jobs:
  linux-x64-python3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-python3
      - name: Download previous build
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/python3-linux-x64.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./nightly.py build --no-update --arch=linux-x64 --target=python3 --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('python3-linux-x64.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket
          artifacts: "python3-linux-x64.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  linux-x64-nextpnr-bba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-nextpnr-bba
      - name: Download previous build
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/nextpnr-bba-linux-x64.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./nightly.py build --no-update --arch=linux-x64 --target=nextpnr-bba --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('nextpnr-bba-linux-x64.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket
          artifacts: "nextpnr-bba-linux-x64.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  linux-x64-prjtrellis-bba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-prjtrellis-bba
      - name: Download previous build
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/prjtrellis-bba-linux-x64.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: ./nightly.py build --no-update --arch=linux-x64 --target=prjtrellis-bba --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('prjtrellis-bba-linux-x64.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket
          artifacts: "prjtrellis-bba-linux-x64.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
  linux-x64-nextpnr-ecp5:
    runs-on: ubuntu-latest
    needs: [ linux-x64-python3, linux-x64-nextpnr-bba, linux-x64-prjtrellis-bba ]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Cache sources
        id: cache-sources
        uses: actions/cache@v2
        with:
          path: _sources
          key: cache-sources-nextpnr-ecp5
      - name: Download previous build
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/nextpnr-ecp5-linux-x64.tgz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvfz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Download linux-x64-python3
        run: wget -qO- "https://github.com/mmicko/test-ci/releases/download/bucket/linux-x64-python3.tgz" | tar xvfz -
      - name: Download linux-x64-nextpnr-bba
        run: wget -qO- "https://github.com/mmicko/test-ci/releases/download/bucket/linux-x64-nextpnr-bba.tgz" | tar xvfz -
      - name: Download linux-x64-prjtrellis-bba
        run: wget -qO- "https://github.com/mmicko/test-ci/releases/download/bucket/linux-x64-prjtrellis-bba.tgz" | tar xvfz -
      - name: Build
        run: ./nightly.py build --no-update --arch=linux-x64 --target=nextpnr-ecp5 --single --tar
      - uses: ncipollo/release-action@v1
        if: hashFiles('nextpnr-ecp5-linux-x64.tgz') != ''
        with:
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          tag: bucket
          artifacts: "nextpnr-ecp5-linux-x64.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
