name: dfu-util

on:
  workflow_dispatch:
jobs:
  dfu-util:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Download a file
        run: |
          wget https://github.com/mmicko/test-ci/releases/download/bucket/dfu-util.tar.gz -O dfu-util.tar.gz
          if [[ $? -eq 0 ]]; then
            tar xvfz dfu-util.tar.gz
            rm dfu-util.tar.gz        
          fi
          /bin/true
      - name: Build
        run: |
          ./nightly.py build --arch=linux-x64 --target=dfu-util
          tar cvfz dfu-util.tar.gz _outputs/linux-x64/dfu-util
      - uses: ncipollo/release-action@v1
        if: hashFiles('dfu-util.tar.gz') != ''
        with:
          allowUpdates: True
          body: ""
          tag: bucket
          artifacts: "dfu-util.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
