name: dfu-util

on:
  workflow_dispatch:
jobs:
  dfu-util:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'yosyshq/fpga-nightly'
      - name: Download a file
        run: |
          URL="https://github.com/mmicko/test-ci/releases/download/bucket/dfu-util.tar.gz"
          if wget --spider "${URL}" 2>/dev/null; then
              wget -qO- "${URL}" | tar xvz -
          else
              echo "Previous version not found in bucket"
          fi
      - name: Build
        run: |
          ./nightly.py build --arch=linux-x64 --target=dfu-util
          tar cvfz dfu-util.tar.gz _outputs/linux-x64/dfu-util
      - uses: ncipollo/release-action@v1
        if: hashFiles('dfu-util.tar.gz') != ''
        with:
          allowUpdates: True
          body: ""
          tag: bucket
          artifacts: "dfu-util.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
